about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('saveSuggestion/', views.saveSuggestion.as_view(), name='save_suggestion'),
]

docinease/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.toHomeView.as_view()),
    path("home/", include("home.urls")),
    path("about/", include("about.urls")),
    path("help/", include("help.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

help/urls.py
from django.urls import path
from . import views

app_name = 'help'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('saveHwFileReturnText/', views.SaveHWFileAndReturnText.as_view(), name='save_hw_file_and_return_text'),
    path('updateHwFileByPostedText/', views.UpdateHandWrittenFileByPostedText.as_view(), name='update_hw_file_by_posted_text'),
    path('returnTextOfAnyHwFile/', views.ReturnTextOfAnyHwFile.as_view(), name='return_text_of_any_hw_file'),
]

about/models.py
from django.db import models

class Suggestion(models.Model):
    content = models.TextField(max_length=100000)

    def __str__(self):
        return self.content[:50]

help/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

class HwPdf(models.Model):
    name = models.CharField(max_length=100, default="dumb")
    content = models.TextField(max_length=5000000000, default="")
    image_file = models.FileField(upload_to="image_files/", null=True, blank=True)
    pdf_file = models.FileField(upload_to="pdfs/", null=True, blank=True)

    def __str__(self):
        return str(self.name[:50])

about/views.py
from django.shortcuts import render, HttpResponse
from django.views import generic
from .models import Suggestion

class IndexView(generic.TemplateView):
    template_name = 'about/index.html'

class saveSuggestion(generic.View):
    def post(self, request):
        
        new_suggestion = Suggestion()
        new_suggestion.content = request.POST['suggest_message_input']
        new_suggestion.save()
        
        return HttpResponse("success")

docinease/views.py
from django.shortcuts import redirect
from django.views import generic

class toHomeView(generic.View):
    def get(self, request): 
        return redirect("home:index")

help/views.py
from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = 'help/index.html'

home/views.py
from django.shortcuts import render, redirect, HttpResponse
from .models import HwPdf
from django.views import generic
from .pdf_gen import return_text_from_given_img, return_pdf_from_given_text
import os
import json

class IndexView(generic.TemplateView):
    template_name = 'home/index.html'

class SaveHWFileAndReturnText(generic.View):
    def post(self, request):
        print("Saving a HW File")
        uploaded_img = request.FILES["hw_upload_input"]
        
        # Creating a New HW but NOT SAVING | FOR ESSENTIAL PATHS
        new_hw_pdf = HwPdf()
        new_hw_pdf.image_file = request.FILES["hw_upload_input"]
        new_hw_pdf.save()

        # essential paths
        image_name = new_hw_pdf.image_file.url.split("/")[3]
        image_name_without_extension = (new_hw_pdf.image_file.url.split("/")[3]).split(".")[0]
        image_url = "media/image_files/" + image_name

        returned_text = return_text_from_given_img(image_url, image_name_without_extension)

        # Saving text to the HW Model Obj
        new_hw_pdf.content = returned_text

        returning_meta = {}

        returning_meta["returned_text"] = returned_text
        returning_meta["item_pk"] = new_hw_pdf.pk

        # Giving the obj a name
        new_hw_pdf.name = returning_meta["returned_text"][:25]
        new_hw_pdf.save()

        return HttpResponse(json.dumps(returning_meta))

class UpdateHandWrittenFileByPostedText(generic.View):
    def post(self, request):
        print("Updating the PDF of Saved Item with a new PDF")
        print(request.POST["posted_item_edited_text"])
        # Creating a New Hand Written Pdf
        grabbed_hw_file = HwPdf.objects.get(pk=request.POST["posted_item_pk"])
        
        # Generating the pdf
        image_name = grabbed_hw_file.image_file.url.split("/")[3]
        image_name_without_extension = (grabbed_hw_file.image_file.url.split("/")[3]).split(".")[0]
        image_url = "media/image_files/" + image_name

        generated_metas = return_pdf_from_given_text(image_url, image_name_without_extension, request.POST["posted_item_edited_text"])

        generated_pdf_path = generated_metas["returning_path"]
        generated_pdf_name = generated_metas["generated_name"]
        
        grabbed_hw_file.pdf_file = generated_pdf_path
        grabbed_hw_file.content = request.POST["posted_item_edited_text"]
        grabbed_hw_file.save()

        # Appending pk of the item to generated_metas
        generated_metas["item_pk"] = grabbed_hw_file.pk
        generated_metas["generated_name"] = grabbed_hw_file.name

        return HttpResponse(json.dumps(generated_metas))

# Return text of any saved HW :BY PK
class ReturnTextOfAnyHwFile(generic.View):
    def post(self, request):
        posted_pk = request.POST['posted_pk']
        item_got = HwPdf.objects.get(pk=posted_pk)
        return HttpResponse(json.dumps(item_got.content))

about/templates/about/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>About | Doc In Ease </title>
    {% load static %}

    <!-- == Google Fonts -->
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- == CSS -->
    <!-- Material CSS -->
    <link rel="stylesheet" href="{% static 'about/materialize/css/materialize.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'about/css/main.css' %}">
</head>
<body>
    <!-- Main Wrapper -->
    <div class="row" id="main-wrapper">
        <!-- ============================================================================== -->
        <!-- Navs -->
        <!-- ================================= -->
        <!-- Navigation Bar At top -->
        <nav class="blue white-text">
            <div class="nav-wrapper">
                <!-- More Button -->
                <ul class="left">
                    <li><a href="#" data-target="slide-out" onclick="openSideNav()"><i class="material-icons">more_vert</i></a></li>
                </ul>
                <!-- Brand Logo -->
                <a href="{% url 'home:index' %}" class="brand-logo"><i class="material-icons">local_printshop</i>DocInEase</a>
                <!-- Other Similar Not Important Buttons -->
                <ul class="right hide-on-med-and-down">
                    <li><a href="#"><i class="material-icons">refresh</i></a></li>
                    <li><a href="#"><i class="material-icons">help_outline</i></a></li>
                </ul>
            </div>
        </nav><!-- ./ Navigation -->
        <!-- ================================= -->
        <!-- Side Nav -->
        <ul id="slide-out" class="sidenav">
            <li><a class="waves-effect" href="{% url 'home:index' %}"><i class="material-icons">local_printshop</i>Home</a></li>
            <li><a class="waves-effect" href="{% url 'help:index' %}"><i class="material-icons">help_outline</i>Help</a></li>
            <li><a class="subheader">DocInEase 2020.02 Update</a></li>
            <li><a class="waves-effect" href="{% url 'about:index' %}"><i class="material-icons">verified_user</i>About</a></li>
        </ul><!-- ./ Slide Nav -->
        <a href="#" data-target="slide-out" class="sidenav-trigger" style="display: none;"><i class="material-icons">menu</i></a>
        <!-- ============================================================================== -->
        <div class="container">
            <!-- About -->
            <div class="card center-align">
                <div class="card-content">
                    <span class="card-title">DocInEase 1.2.2</span>
                    <p>You are using DocInEase Latest February Update. Doc In Ease. Document Made Easy To Convert To a PDF. Our Goal is to make people's life easier with this tool. Thanks alot for using this tool. We will dedicate to our fullest to provide the user with better experience. We are The TechLio Team. If you have any concerns, feedbacks or suggestions please post below.</p>
                    <!-- Form Form Suggestions foing -->
                    <form>
                        {% csrf_token %}
                        <div class="input-field col s12">
                            <input id="suggest_message_input" type="text" class="validate">
                            <label for="suggest_message_input">Concerns | Feedbacks | Suggestions for improving the next version</label>
                        </div>
                        <button class="btn blue right waves-effect waves-light" onclick="sendMessage()" type="button">Send Message</button>
                    </form>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div><!-- ./Main Wrapper -->


    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- Material JS -->
    <script src="{% static 'about/materialize/js/materialize.min.js' %}"></script>
    <!-- Material Init -->
    <script src="{% static 'about/materialize/js/inits.js' %}"></script>
    <!-- Jquery -->
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <script src="{% static 'about/js/main.js' %}"></script>
</body>
</html>

help/templates/help/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Help | Doc In Ease </title>
    {% load static %}

    <!-- == Google Fonts -->
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- == CSS -->
    <!-- Material CSS -->
    <link rel="stylesheet" href="{% static 'help/materialize/css/materialize.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'help/css/main.css' %}">
</head>
<body>
    <!-- Main Wrapper -->
    <div class="row" id="main-wrapper">
        <!-- ============================================================================== -->
        <!-- Navs -->
        <!-- ================================= -->
        <!-- Navigation Bar At top -->
        <nav class="blue white-text">
            <div class="nav-wrapper">
                <!-- More Button -->
                <ul class="left">
                    <li><a href="#" data-target="slide-out" onclick="openSideNav()"><i class="material-icons">more_vert</i></a></li>
                </ul>
                <!-- Brand Logo -->
                <a href="{% url 'home:index' %}" class="brand-logo"><i class="material-icons">local_printshop</i>DocInEase</a>
                <!-- Other Similar Not Important Buttons -->
                <ul class="right hide-on-med-and-down">
                    <li><a href="#" onclick="refreshThePageOrItsItems()"><i class="material-icons">refresh</i></a></li>
                    <li><a href="#"><i class="material-icons">help_outline</i></a></li>
                </ul>
            </div>
        </nav><!-- ./ Navigation -->
        <!-- ================================= -->
        <!-- Side Nav -->
        <ul id="slide-out" class="sidenav">
            <li><a class="waves-effect" href="{% url 'home:index' %}"><i class="material-icons">local_printshop</i>Home</a></li>
            <li><a class="waves-effect" href="{% url 'help:index' %}"><i class="material-icons">help_outline</i>Help</a></li>
            <li><a class="subheader">DocInEase 2020.02 Update</a></li>
            <li><a class="waves-effect" href="{% url 'about:index' %}"><i class="material-icons">verified_user</i>About</a></li>
        </ul><!-- ./ Slide Nav -->
        <a href="#" data-target="slide-out" class="sidenav-trigger" style="display: none;"><i class="material-icons">menu</i></a>
        <!-- ============================================================================== -->
        <div class="container">
            <!-- Introduction -->
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Introduction to our tool</span>
                    <p>What we are trying to achieve is to give the user the full potential to use OCR (Optical Character Recognition) technology as they wanted. With OCR the user will be able to convert their handwritten documents into typed pdf files. So we are continuously working to improve the product</p>
                </div>
            </div>
            <!-- How to convert -->
            <div class="card">
                <div class="card-content">
                    <span class="card-title">How To Convert Handwritten Text To PDF files?</span>
                    <p>Just tap on the upload button and select the handwritten document image. After doing that tap on the proceeding button. Then in a few seconds, your document will be converted into a PDF file.</p>
                </div>
            </div>
            <!-- Tool Manipulation -->
            <!-- How to convert -->
            <div class="card">
                <div class="card-content">
                    <span class="card-title">Manipulation of Saved PDF files</span>
                    <p>So after uploading the handwritten document and saving it as a PDF, You'll have the options to view info, print and download the generated PDF file. </p>
                </div>
            </div>
            <!-- How to Print -->
            <div class="card">
                <div class="card-content">
                    <span class="card-title">How to Print Generated PDF file</span>
                    <p>All you have to do is tap on the print button of the relavant PDF file and the hit the (Ctrl + P)</p>
                </div>
            </div>
            <!-- How to Download -->
            <div class="card">
                <div class="card-content">
                    <span class="card-title">How to Print Generated PDF file</span>
                    <p>All you have to do is to tap on the download button of the relavant PDF file</p>
                </div>
            </div>
        </div>
    </div><!-- ./Main Wrapper -->


    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- Material JS -->
    <script src="{% static 'help/materialize/js/materialize.min.js' %}"></script>
    <!-- Material Init -->
    <script src="{% static 'help/materialize/js/inits.js' %}"></script>
    <!-- Jquery -->
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    <!-- Custom JS -->
    <script src="{% static 'help/js/main.js' %}"></script>
</body>
</html>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home | Doc In Ease - Smart Documenting AI For Converting Handwritten Documents to Actual PDFs</title>
    {% load static %}

    <!-- == Google Fonts -->
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- == CSS -->
    <!-- Material CSS -->
    <link rel="stylesheet" href="{% static 'home/materialize/css/materialize.min.css' %}">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
    <!-- Custom Elements For HW Inline Editor -->
    <style>
        s_underline{
            text-decoration: underline;
        }
        s_strike{
            text-decoration: line-through;
        }
        s_indent{
            display: inline-block;
            text-indent: 10px !important;
        }
        s_italic{
            font-style: italic;
        }
        s_align_left{
            display: block !important;
            width: 100% !important;
            text-align: left !important;
        }
        s_align_center{
            display: block !important;
            width: 100% !important;
            text-align: center !important;
        }
        s_align_right{
            display: block !important;
            width: 100% !important;
            text-align: right !important;
        }
        s_list_un::before{
            content: "⚫";
        }
    </style>
</head>
<body onload="onLoadShowPreloader();">
    <!-- ======================================================================================== -->
    <!-- On Load The Preloader We Gonna Show ^^ -->
    <div id="onload-preloader">
        <img src="{% static 'home/img/document_gif_preloader.gif' %}">
        <p>Loading Doc In Ease. Please wait...</p>
        <div class="progress blue lighten-3">
            <div class="indeterminate blue darken-2"></div>
        </div>
    </div>
    <!-- ======================================================================================== -->
    <!-- Main Wrapper -->
    <div class="row" id="main-wrapper">
        <!-- !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! -->
        <!-- Navs -->
        <!-- ================================= -->
        <!-- Top Nav Bar -->
        <nav class="blue white-text" id="nav-bar">
            <div class="nav-wrapper">
                <!-- More Button: Expands -->
                <ul class="left">
                    <li><a href="#!" data-target="slide-out" onclick="openSideNav()"><i class="material-icons">more_vert</i></a></li>
                </ul>
                <!-- Brand Logo: Branding -->
                <a href="{% url 'home:index' %}" class="brand-logo"><i class="material-icons">local_printshop</i>DocInEase</a>
                <!-- ETCs Buttons -->
                <ul class="right hide-on-med-and-down">
                    <li><a href="#"><i class="material-icons" onclick="openSearchBox()">search</i></a></li>
                    <li><a href="#"><i class="material-icons" onclick="refreshThePageOrItsItems()">refresh</i></a></li>
                    <li><a href="{% url 'help:index' %}"><i class="material-icons">help_outline</i></a></li>
                </ul>
            </div>
        </nav> <!-- ./ Top Navigation -->
        <!-- ================================= -->
        <!-- Search Nav Bar: Hidden -->
        <nav class="blue" id="search-nav-bar" style="display: none;">
            <div class="nav-wrapper">
                <form>
                    <div class="input-field">
                        <input id="search" type="search" required oninput="searchingSubmission()">
                        <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                        <i class="material-icons" onclick="closeSearchNavBar()">close</i>
                    </div>
                </form>
            </div>
        </nav>
        <!-- ================================= -->
        <!-- Side Nav: On Click For More Button -->
        <ul id="slide-out" class="sidenav">
            <li><a class="waves-effect" href="{% url 'home:index' %}"><i class="material-icons">local_printshop</i>Home</a></li>
            <li><a class="waves-effect" href="{% url 'help:index' %}"><i class="material-icons">help_outline</i>Help</a></li>
            <li><a class="subheader">DocInEase 2020.02 Update</a></li>
            <li><a class="waves-effect" href="{% url 'about:index' %}"><i class="material-icons">verified_user</i>About</a></li>
        </ul><!-- ./ Side Nav -->
        <a href="#" data-target="slide-out" class="sidenav-trigger" style="display: none;"><i class="material-icons">menu</i></a>
        <!-- ============================================================================== -->
        <!-- Upload A New Handwritten -->
        <section class="row center-align" id="hw_upload_section">
            <!-- Heading -->
            <h6 id="hw_upload_h6">Upload to Convert</h6>
            <!-- Thumbnail Holder for uploading img -->
            <img src="" id="hw_upload_thumbnail" class="responsive-img">
            <br>
            <!-- Image Select Button and Image Open With Editor Button -->
            <button id="hw_upload_clown_btn" class="btn blue btn-floating btn-large waves-effect waves-light" onclick="clickOnHwFileInput()"><i class="material-icons">cloud_upload</i></button>
            <button id="hw_editor_open_btn" class="btn blue btn-floating btn-large waves-effect waves-light" onclick="hwFileUploadOpenWithEditor(true)"><i class="material-icons">chrome_reader_mode</i></button>
            <!-- Hand Written File Hidden Input -->
            <form method="POST" enctype="multipart/form-data" id="hw_upload_form">
                {% csrf_token %}
                <input type="file" style="display: none;" name="hw_upload_input" id="hw_upload_input">
            </form>
        </section>
        <br>
        <br>
        <!-- Upload A New Handwritten Preloader -->
        <section class="row center-align" id="hw_upload_preloader_section" style="display: none;">
            <div class="preloader-wrapper big active">
                <div class="spinner-layer spinner-blue-only">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="gap-patch">
                        <div class="circle"></div>
                    </div><div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Opening the editor with generated text...</p>
        </section>
        <br>
        <!-- ======================================================================== -->
        <!-- Saved Starts -->
        <div class="row center-align">
            <h5>Saved Documents</h5>
        </div>
        <section class="row center-align" id="saved-documents-section">
            <!-- =============================== -->
            <!-- ICON LIST -->
            <!-- =============================== -->
        </section>
    </div>
    <!-- csrf token for later use -->
    {% csrf_token %}
    <!-- Later Use -->
    <script>
        let hwUploadSectionTemplate = `
            <h6 id="hw_upload_h6">Upload to Convert</h6>
            <!-- Thumbnail Holder for uploading img -->
            <img src="" id="hw_upload_thumbnail" class="responsive-img">
            <br>
            <button id="hw_upload_clown_btn" class="btn blue btn-floating btn-large waves-effect waves-light" onclick="clickOnHwFileInput()"><i class="material-icons">cloud_upload</i></button>
            <button id="hw_editor_open_btn" class="btn blue btn-floating btn-large waves-effect waves-light" onclick="hwFileUploadOpenWithEditor(true)"><i class="material-icons">chrome_reader_mode</i></button>
            <!-- Hand Written File Hidden Input -->
            <form method="POST" enctype="multipart/form-data" id="hw_upload_form">
                {% csrf_token %}
                <input type="file" style="display: none;" name="hw_upload_input" id="hw_upload_input">
            </form>
        `;
    </script>
    <!-- Sweet Alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <!-- Material JS -->
    <script src="{% static 'home/materialize/js/materialize.min.js' %}"></script>
    <!-- Jquery -->
    <script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
    <!-- Material Init -->
    <script src="{% static 'home/materialize/js/inits.js' %}"></script>
    <!-- @@@@@@@@@@@@@@@ Custom JS -->
    <script src="{% static 'home/js/1_on_load_content.js' %}"></script>
    <script src="{% static 'home/js/2_general.js' %}"></script>
    <script src="{% static 'home/js/3_navs.js' %}"></script>
    <script src="{% static 'home/js/4_hw_upload.js' %}"></script>
    <script src="{% static 'home/js/5_hw_editor.js' %}"></script>
</body>
</html>